spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: pavel
    password: pavel
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  profiles:
    active: prod
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 40
cache:
  algorithm: LRU
  capacity: 5
aop:
  logging:
    enabled: true
exception:
  handling:
    enabled: true
base:
  url:
    users: http://localhost:8081/users
